FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# xo-achiev

xo-achiev is simple API that allows saveing and getting user achievements.


# xo-achieve API Root [/]


## Add User Score [PUT/{id}]

You may update or create user data with specified score.
It takes JSON object

- score (required,int) - Score that user got. 


+ Parameters
    + id    (required,int) -  user id


+ Request (application/json)

    + Body
    
            {
                "score" : 100
            }

+ Response 200

## Retrive a single user achievment [GET/{id}]

Returns object with user score and rank.

+ Parameters
    + id (required, int, `1023`) user id
    
+ Response 200 (application/json)

            {
                "score" : 100,
                "rank" : 10,
            }
